/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommentPopup: typeof import('./components/CommentPopup/index.vue')['default']
    DrawerPlayer: typeof import('./components/DrawerPlayer/index.vue')['default']
    Footer: typeof import('./components/layout/Footer/Footer.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    LocalhostSong: typeof import('./components/layout/Footer/components/localhostSong.vue')['default']
    LoginDialog: typeof import('./components/LoginDialog.vue')['default']
    MusicList: typeof import('./components/MusicList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/layout/SideBar.vue')['default']
    TabBar: typeof import('./components/TabBar.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    Volume: typeof import('./components/layout/Footer/components/volume.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
